name: Monthly links update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # This schedules the workflow to run on the 1st day of every month

permissions:
  contents: write

jobs:
  run-zipcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the version of Python you need

    - name: Remove old list
      run: rm workinglinks.txt

    - name: Create a new up-to-date list
      run: python zipcheck.py

    - name: Commit list update
      uses: EndBug/add-and-commit@v5
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}